### ISSUE TITLE
FilteringSelect

### ISSUE THREAD

**Issue by AlexRFS** [Alfresco/Aikau#1295] opened 2016-11-17 13:41 UTC
Hello, i have FilteringSelect defined like this:
```JAVASCRIPT
{
        name : "alfresco/forms/controls/FilteringSelect",
        config : {
            fieldId : "FILTERING_SELECT_1",
            name : "person1",
            label : "Select a person a",
            optionsConfig : {
                queryAttribute : "label",
                labelAttribute : "label",
                valueAttribute : "value",
                publishTopic : "ALF_GET_FORM_CONTROL_OPTIONS",
                publishPayload : {
                    resultsProperty : "options",
                    url: url.context + "/proxy/alfresco/dfi/GetListData?siteName=legal&listName=Locations&columnsReturn=dfildf:Location", //&listName=Locations&columnsReturn=dfildf:Location"
                    itemsAttribute : "items",
                    labelAttribute : "dfildf:Location",
                    valueAttribute : "nodeRef"
                }
            }
        }
    };
```
All ok, but when page is loaded there is the first element selected in this control, and when i click the arrow button to select another option there are no items available to select. But if i remove current value and click this arrow items are available to select.

**Comment by draperd** [comment] 2016-11-17 13:56
First of all, thanks for raising this issue... however, it would be really helpful if you could provide the version of Aikau that you're using. Are you using a default version shipped with Alfresco (if so which version) or are you using a later release?

**Comment by AlexRFS** [comment] 2016-11-17 14:06
Dave, thanks for your quick response.
I'm using 1.0.85 version aikau

**Comment by draperd** [comment] 2016-11-17 14:11
Thanks...

I've just read the description again... I actually think that this might be a "feature" of the underlying control that is being rendered. So the reason that no other options might not be showing is because the options are always filtered against the current value. Is that what you're experiencing?

This would mean that as you delete characters the options appear that have a stem of the current value.

i.e. if the value is "Hello" you would see options like "Hello World", "Hello Goodbye", but once the value is "Hello W" then you no longer see "Hello Goodbye" (hopefully that rather odd example makes sense)

**Comment by AlexRFS** [comment] 2016-11-17 14:20
Dave,
Yes, it is.
I have looked on diji FilteringSelect, on which this aikau widget based. [Here the link](http://dojotoolkit.org/documentation/tutorials/1.10/selects/index.html)
And as you can see here it is still working  despite that fact, that some value is selected

**Comment by draperd** [comment] 2016-11-17 14:51
OK, thanks you're right... I'll take a look and see if I can figure out why it's not working as it should. Thanks for raising this.

**Comment by AlexRFS** [comment] 2016-11-17 14:58
Dave, and one more remark...
Could you see too why this control raises four requests(get data) when page is loaded instead of one

thanks

**Comment by draperd** [comment] 2016-11-17 15:04
OK, will do.

**Comment by draperd** [comment] 2016-11-17 17:26
With regards to the latter issue, I've had a bit of an investigation and it's because the alfresco/forms/controls/utilities/ServiceStore mixin (which FilteringSelect uses) make an initial request... we also make a request when all BaseFormControls are created (those that use the ServiceStore can be updated to avoid this) and a request is made each time the value is set, so once by the initial value and once when the outer form sets the value. I think I can get this down to just the one request providing that I can do so in a way in which doesn't break options handling of other form controls, but I think this should be possible.

I'm not sure if I'll be able to get this into the next release (I was planning on releasing tomorrow) but it should make the following release.

**Comment by draperd** [comment] 2016-11-17 17:26
...I think the former issue is to to with the queryExpr configured for the inner FilteringSelet (the Dojo one) but I'm not 100% sure yet.

**Comment by draperd** [comment] 2016-11-17 18:04
I've raised https://issues.alfresco.com/jira/browse/AKU-1128 and https://issues.alfresco.com/jira/browse/AKU-1129 to address each of these issues. If you have a JIRA account I can assign you as the reporter if you'd like to more easily track progress.

**Comment by AlexRFS** [comment] 2016-11-17 19:05
Thanks Dave,
My Jira account is alexrfs.
Add me please as reporter.
And about the former issue I have the same suggestion... Will wait..

**Comment by draperd** [comment] 2016-11-18 11:38
I've fixed the latter option (which will be in a release later today) but I don't think I'm going to get the other issue fixed today, primarily because I'm not sure about the correct way to approach this with regards to backwards compatibility...

I've obviously addressed this at some point in the past given the existence of the following code from the ServiceStore module:

```JAVASCRIPT
/**
 * In vanilla Dojo, when you open either a ComboBox or FilteringSelect you will
 * get all options, not those filtered on the current form control value. This
 * function can be called to override the default _startSearchAll function
 * with one that uses the current value.
 *
 * @instance
 */
showOptionsBasedOnValue: function alfresco_forms_controls_utilities_UseServiceStoreMixin__showOptionsBasedOnValue(control) {
   control._startSearchAll = lang.hitch(control, this.searchAll);
},
```

So I need to try to work back through the change logs to make sure I don't undo a requirement made by one of the feature delivery teams. (However, I'm not entirely sure that this is working as intended!)

As a further FYI... I just wanted to make you aware of the `searchStartsWith` attribute that can be configured on the `optionsConfig` object to allow text matching to be done anywhere within the options value (I'm not suggesting this fixes your problem at all, just wanted to make you aware it was there as you're working with this widget).

**Comment by AlexRFS** [comment] 2016-11-18 12:09
Hi Dave, thanks, i will wait when you will finished your review..

**Comment by draperd** [comment] 2016-11-18 14:22
I've actually decided to squeeze this into the release... I've made the decision to respect how the previous versions have worked (changing behaviour in the past has usually caused trouble somewhere unexpected so I take the safe policy of retaining how things worked before). Therefore in order to get the behaviour that you require you'll need to configure the `showAllOptionsOnOpen` attribute of the FilteringSelect to be `true`.

**Comment by draperd** [comment] 2016-11-18 14:57
Both fixes are available in the 1.0.96 release which is now available.

**Closed by draperd** 2016-11-18 14:57 UTC

**Comment by AlexRFS** [comment] 2016-11-18 15:26
Big thanks Dave

**Comment by draperd** [comment] 2016-11-18 15:32
You're very welcome - thanks for raising these issues, this kind of feedback is absolutely invaluable!
