### ISSUE TITLE
Rendering of large widget structures / AlfList views can take a very long time

### ISSUE THREAD

**Issue by AFaust** [Alfresco/Aikau#958] opened 2016-03-28 22:00 UTC
The current way that complex, nested widget structures are rendered includes various inefficiencies that appear to have a nasty, non-linear effect on the time it takes to render e.g. a list of 50 entries with 50 very simple columns.

The demonstrator test case in my gist https://gist.github.com/AFaust/1d1450ffe8829371ad04 renders such a list of 50 entries with 50 columns. On IE 11 it can take around 30 seconds for the initial rendition. Firefox (45) appears to be better at handling the use case with around 6-10s. Since I don't use (or even install) Chrome, I can't say how it fares.
In other use cases when we have used a paginating, sortable list, we've additionally observed that destroying the previous page can also take a significant time (~5s on IE11 for a 50 rows and ~20 coumns case).

Sure, any use case that involves excessive complexity can expect to suffer some performance degredation. But it is hard to explain to an end-user / customer, why only 50x50 values are enough to grind his web app to a halt.

In the last week and a half I have built completely separate "high performance" variants of the ListRenderer, Row, Cell, Property and InlineEditProperty widgets (and mixins CoreWidgetProcessing / MultiItemRendererMixin), and also applied some optimisations to secondary widgets such as the Actions renderer, to effectively bring down rendering time to ~10-15% and nearly eliminate overhead of destroying the previous list page.

The main issues we identified as causing significant overheads were:
- construction of the entire view in the live DOM (i.e. each widget is attached to the live DOM during dijit/_WidgetBase create() and only then are children processed)
- use of replacement tokens in widget HTML templates disables caching in dijit/_TemplatedMixin
- synchronous destruction of the entire view while still in the live DOM
- relatively expansive workaround in Dojo 1.10 dom-construct _empty() for potential memory leak in IE <= 9 (https://github.com/dojo/dojo/blob/master/dom-construct.js#L304)
- generic processing of widget template for potential attach points / events (scales with number of tags in HTML)
- premature initialization of secondary widgets / DOM structures that may not be used on every element (Actions menu, inline edit DOM fragments, which could be initialized on the first "mouse hover" of a duration of 100ms or more)
- application of inline styles (declared in widget config) on each instance instead of using dynamically applied CSS rules, i.e. using a shared cell/column/property identifier
- evaluation / application of ALL declarative widget config parameters as potential DOM attributes in dijit/_WidgetBase _applyAttributes even though 99+% are typically irrelevant
- repeated construction of dateFormats in alfresco/core/TemporalUtils (could be cached by i18nScope)
- inclusion of WidgetInfo debug widget on every level (it would be nice if that could be declaratively disabled for an entire sub-structure of widgets in the JSON model, even in debug mode)

The primary changes I have included in our widget / mixin variants are:
- introduction of new lifecycle hooks postAttach (when widget is added to live DOM) and prepareDestroy (when widget is about to be destroyed)
- default prepareDestroy will unsubscribe / remove all event registrations
- redefinition of destroy to synchronously detach widget (and substructure) from live DOM, call prepareDestroy on self, call either prepareDestroy/destroy on any children (depending on support of new lifecycle hook) and schedule for asynchronous "real" destruction
- use detached documentFragment nodes to collect all widgets during a processWidgets() call and only attach to live DOM when all widgets have been processed (including children structures)
- (recursively) call postAttach on any (compatible) widget when it has been attached to the live DOM (via the containing documentFragment)
- replaced use of HTML templates with dynamically constructed DOM (custom buildRendering()) and explicit variable / event attachment for very frequently used widgets (Row, Cell, Property, InlineEditProperty)
- dynamically create CSS rules for inline styles of widgets when configured with a special property (a 'dynamicCssRuleClass' name to bind the rules to, which is combined with the class name of our custom root widget module variant)
- delayed initialization of secondary functionality (InlineEditProperty edit icon + hover, Actions menu) until user is hovering on actual widget for at least 100ms
- added parameter for declarative JSON model to explicitly disable WidgetInfo even in debug mode (defaults to true in our high performance widget / mixin variants)

I won't suggest that the majority of my changes need to be included in / considered for Aikau core, but I feel very strongly about the need for an enhanced widget lifecycle, especially for potentially nested / large widget structures. Both the construction in detached DOM and asynchronous destruction in a detached DOM had the most significant impact on overall performance when we ignore the HTML widget template / event attachment overhead, which could be addressed on a widget-by-widget basis outside of Aikau core.

The following screenshots showcase the profiling results of the test case from my gist, running in IE 11 (Win 7 64bit), on Alfresco 5.0.3 and Aikau 1.0.60

![aikau-large-list-render-perf-ieresponsiveness](https://cloud.githubusercontent.com/assets/2211521/14090849/facfc722-f53c-11e5-91d5-fe2e1f9e532b.png)
![aikau-large-list-render-perf-ieprofiler](https://cloud.githubusercontent.com/assets/2211521/14090855/ff8107cc-f53c-11e5-94db-da4378abe2c5.png)
![aikau-large-list-render-perf-ieprofiler-domaccess](https://cloud.githubusercontent.com/assets/2211521/14090857/0319c928-f53d-11e5-922a-0223bf12f721.png)
![aikau-large-list-render-perf-ieprofiler-widgetbase_create-calltree](https://cloud.githubusercontent.com/assets/2211521/14090859/0620ebce-f53d-11e5-8325-8a5eacb4e252.png)

**Comment by draperd** [comment] 2016-03-29 08:00
OK. So this is all great stuff... in all honesty, performance has never been my major priority - it was always something I hoped we'd be able to get back to. However, my initial observation on reading this is .... wow, this is going to be a lot to absorb!

Naturally I'm also concerned about backwards compatibility - where you have entirely distinct widgets then we can easily absorb them as new modules without any impact, but where you're proposing changes to key mixin modules then we need to tread more carefully. Have you run the existing unit test suite against any of these changes? Or are these just focused on the use case that you've provided in your Gist? Can we look at breaking these down into smaller pull requests or do they need to be taken altogether?

The other obvious difficulty is in not actually being able to see the code changes that you've made. It might make sense for you to create a pull request of everything just so that we can review and experiment with it. Although we might not merge that request, we can use it as a means to establish how to move this forwards.

Hopefully you can understand the need to take our time over major changes to the internal codebase - it is also imperative that the Alfresco team understand the changes as we need to be able to support the changed code.

Having said all that - we definitely want to move forwards on this, assuming everything is as good as you say it is and doesn't cause any backwards compatibility issues. If you can raise the pull request so that we can start reviewing proposed changes then that would be a great place to start.

We're committed to making Aikau a proper open-source project and accepting contributions from the community though - and we're grateful that you've taken the time to make this effort.

**Comment by AFaust** [comment] 2016-03-29 08:12
The changes I made the last week and a half were completely distinct from the core widgets - I basically re-created the widgets and adapted the mixins via sub-classing. So the standard unit tests would not cover those. Our widgets also contain a few other feature additions / changes to the default widgets that they aren't really comparable anymore (i.e. we removed the Property tooltip handling in favor of standard DOM title attribute to reduce layout calculation overhead, extracted Property/InlineEditProperty/PropertyLink/Boolean features into three separate mixins ("RenderSupport", "LinkSupport", "EditSupport") and recombined those into a single, universal Property widget).

What I can definitely do (might get to it next weekend) is "liberate" our changes from the custom widgets / mixins and generalise them into the core widgets / mixins as a branch/PR to compare against. Then I can also run the existing unit tests...
My primary concern with this ticket was to raise the performance issues / concerns with you as early as possible.

**Comment by draperd** [comment] 2016-03-29 08:23
OK, cool... I'm just very happy that you're looking to contribute back into Aikau. As I said, I always knew we'd be able to improve performance - but we needed to get other things in place first (breadth of widgets, testing, etc). Looking forward to seeing some code!

**Comment by AFaust** [comment] 2016-04-11 15:08
The branch [Aikau-958](https://github.com/AFaust/Aikau/tree/Aikau-958) in my fork contains the "liberated" and generalised changes from our internal module that are sufficient to run the test case I used in this ticket (additional changes would be required to make some derived widgets work, i.e. InlineEditProperty).
As part of this I have created a "BaseWidget" module as a pendant to the BaseService, and introduced a _ConstructedWidgetMixin module for any widgets that do not use HTML templates. The CoreWidgetProcessing mixin has been enhanced with (optional) support of detached DOM initialisation of children which relies on the lifecycle functions provided by BaseWidget. This  behaviour is automatically active when the widget that includes the mixin is a BaseWidget, and it can also be explicitly forced.
The WidgetInfo widget can now be suppressed for a specific widget and I have also included the relevant flag in the auto-inheritance of configuration properties if not set explicitly.

Somewhere during this "liberation", the improvements lost some of their effectiveness. Current profiling runs indicate that these changes only end up in a gain of around / below 25%, where in our module we achieved significantly better results (although we used a significantly more complex JSON page model with more complex widgets). One thing I have not "liberated" yet is our feature to transform inline-style attributes from JSON configuration into runtime CSS rules.

![aikau-branch-aikau-958-perf-ieresponsiveness](https://cloud.githubusercontent.com/assets/2211521/14431815/b35783fa-0007-11e6-9a61-2d42da88d85d.png)

I'll do some more analysing of where I lost some of the effectiveness of the changes, but at least you now have a reference of what we (essentially) did.

**Comment by draperd** [comment] 2016-04-11 15:46
OK... thanks - I'll clone your forked repo and take a look at the changes you've made

**Comment by draperd** [comment] 2016-04-12 09:09
I've raised https://issues.alfresco.com/jira/browse/AKU-930 for us to cover investigating and merging the proposed changes into the Aikau code. It's currently planned for our next sprint.

**Comment by draperd** [comment] 2016-04-13 09:16
OK... I've started to take a look at the proposed changes. My plan was to check out the branch provided, build it and then run the unit tests.

Unfortunately I hit a few conflicts in ListRenderer which I believe I've resolved correctly, however it seems like there are a lot of problems that are present on the branch (https://github.com/Alfresco/Aikau/tree/AKU-931_Performance) the unit test index page is not rendering correctly (there are no links displayed - just properties). I hit a few unit test pages at random and all seemed to have issues.

It might be worth you inspecting my branch to see that you're happy that I've resolved the conflicts as you've expected. Also, if you have time it might be useful to see if you can debug any of the issues - just getting the unit test index page running properly would be a good step. 

I'll kick off a full regression test and see how many additional errors it throws up.

**Comment by draperd** [comment] 2016-04-13 13:57
I've added test failures to https://issues.alfresco.com/jira/browse/AKU-931

**Comment by AFaust** [comment] 2016-04-13 13:57
I thought I mentioned it, but the changes on the branch were meant to be sufficient to run the test case of this ticket (the one in my gist) and showcase the performance differences. By no means were they meant to be complete, i.e. result in (all) existing unit tests to be run successfully.I explcitly mentioned that derived widgets (such as InlineEditProperty) would likely need to be adapted, but could have been more liberal and used a warning in **bold** text.
Since the poor quality of Node / Node-related libraries broke my use of maven-frontend-plugin, I won't be able to run any of those until I have had time to setup a VM for that...

**Comment by AFaust** [comment] 2016-04-13 14:03
That's an interesting list of failures. For some I can't think of how those could even have been affected by the change...

**Comment by draperd** [comment] 2016-04-13 14:04
OK ... sorry, I must have missed that... I do obviously want to get the performance improvements in (if for no other reason than to demonstrate that we are willing to accept contributions!). I'll come back to this at the end of the sprint and look to see what code we can safely take from the changes you've proposed.

**Comment by draperd** [comment] 2016-04-15 11:11
Another update... I've been looking through the code changes and your performance review in more detail (which is excellent, thank you for that). I'm in complete agreement that we need to tackle these things, unfortunately as you'd originally indicated (but I'd not fully absorbed) the changes can't be merged as they currently are because they break too many other things.  The one thing I think we can definitely take without change is the date caching improvements.

The ideas your code pushes are really good, I just need to find a way to incorporate them without breaking too many other things. I'll continue to work on this for the rest of the current sprint and try and plan away to move forward by tackling specific areas without causing too much disruption.

**Comment by draperd** [comment] 2016-04-15 15:53
I've made some progress... the cleanup at the end of _registerProcessedWidget was breaking promise resolution, removing that got a few things working agai (but presumably introduces potential memory issues). Switching back to the original model based AlfDetailedView code worked as well. There's still quite a lot of things broken though - I'll dig into those next week.

**Comment by draperd** [comment] 2016-11-18 14:59
I've merged the future version of generating child widgets in a new development package called `aikau` which is available in the 1.0.96 release. I'd appreciate you reviewing this code (from a performance point of view) as I start to create more widgets that use it. FYI... I haven't addressed the templating overhead concerns yet.

**Comment by draperd** [comment] 2016-12-01 10:39
FYI... I'm starting to investigate this issue under https://issues.alfresco.com/jira/browse/AKU-878. I've set up a sample performance test page (that renders a list that is 100 rows by 50 cells with a single property rendered in each). I'm profiling the page and trying to squash the problems in a way that will be backwards compatible.

**Comment by draperd** [comment] 2016-12-15 08:08
I'm going to close this issue now following the updates made in the 1.0.101 release as described in this post: https://community.alfresco.com/community/ecm/blog/2016/12/12/improving-aikau-performance

**Closed by draperd** 2016-12-15 08:08 UTC
