### ISSUE TITLE
Create a button who acts on all the results in a AlfSearchList or AlfList

### ISSUE THREAD

**Issue by shazada** [Alfresco/Aikau#688] opened 2015-11-19 15:56 UTC
What I've seen so far there is only the publishPayloadType: "CURRENT_ITEM" which works fine on the item in a list.

My goal is to create a button on a AlfSearchList in this case which takes all the results and send it to a repo call and fire an Action.
So what I've done so far:
```javascript
var widget = widgetUtils.findObject(model.jsonModel.widgets, "id", "FCTSRCH_RESULTS_MENU_BAR");
var action = {
    name: "alfresco/buttons/AlfButton",
    config: {
        label: "DOWNLOAD EVERYTHING",
        publishTopic: "ALF_DOWNLOAD_AS_ZIP",
        subscriptionTopic: "ALF_SEARCH_REQUEST",
        publishPayload: {
            documents: "data"
        }
    }
};
widget.config.widgets.push(action);
```

So how this button should work in theory is that it should fire Topic ALF_DOWNLOAD_AS_ZIP with the data of ALF_SEARCH_REQUEST.

It would be great if there is an extra predefined publishPayloadType like "ALL_ITEMS".

**Comment by draperd** [comment] 2015-11-19 17:26
OK... if you can put aside that the caveat that it would simply not be possible to get all the results of a matching search request due to the pagination limitations of the search API (i.e. unless you have a highly specific search then you can't guarantee that the all the search results will be in the response of the search request)...

...also, it's worth remembering that as Aikau is abstract so isn't written with respect to specific implementations (however you're quite at liberty to easily write your own highly specialized button by extending the existing AlfButton...

...but having said all that there are multiple approaches to doing this...

1) The AlfSearchResult now supports "showSelector" which if configured to be true will render a checkbox. It's also possible to include a "alfresco/documentlibrary/AlfSelectedItemsMenuBarPopup" in the existing menu bar on the search page and place action items into it that publish the topics.SELECTED_DOCUMENTS_ACTION topic (where the payload contains an "actionTopic" attribute). This will then allow actions to be performed on the items that have been selected.

2) When search results are displayed they are published on the "ALF_RETRIEVE_DOCUMENTS_REQUEST_SUCCESS" topic. We already have a alfresco/buttons/AlfDynamicPayloadButton button that can subscribe to topics and map the received payload to the payload it will publish when clicked. This means that you can create an AlfDynamicPayloadButton that subscribes to "ALF_RETRIEVE_DOCUMENTS_REQUEST_SUCCESS" can map the search results to the payload of the button so that when it is clicked it publishes the appropriate payload on the topics.DOWNLOAD_AS_ZIP topic.

Also, it's possible to create a custom service that tracks the available items or selected items (using the alfresco/lists/SelectedItemStateMixin mixin module) to handle that.

There are many different ways in which this could be resolved - Aikau is provided to facilitate these types of customization rather than addressing every different use case and I'm not sure that this is a generic enough requirement for us to implement directly. It's unlikely to be prioritized very highly on our current backlog if it is raised as a feature request on JIRA.

Depending on how quickly you need this item turned around will determine how you should approach it, either requesting we raise a feature request and waiting until it gets done or tackling it yourself using one of the approaches described above.

**Comment by shazada** [comment] 2015-11-20 08:06
Thanks David for the answer!

I've lookad at 1) using the showSelector, but this has 2 flaws in this case. 1 I need to first select all clicking on the button before sending it to the action (or set the default to selected, which isn't that good looking). 2 It isn't good looking if you know already that you'll select all at all times :).

I haven't looked at 2), so I'll do that.

And how about the idea to capture the searchTerm in that button send that to a custom Repository script which does the search first and then does the download?

This is probably also possible with the AlfDynamicPayloadButton right? I can just change the Publish url to a custom url and subscribe on a Topic which contains the searchterm.

**Comment by shazada** [comment] 2015-11-20 15:32
Hi David,

I'm a bit further with this approach, but I can't seem to get the payload aka the result items.

var actionDynamic = {
    name: "alfresco/buttons/AlfDynamicPayloadButton",
    config: {
        label: "DOWNLOAD EVERYTHINGOS",
        publishTopic: "ALF_DOWNLOAD_AS_ZIP",
        subscriptionTopic: "ALF_RETRIEVE_DOCUMENTS_REQUEST_SUCCESS",
        publishPayload: {
            documents: "items"
        }
    }
};

Even if I use the payload as:
 publishPayload: {
            documents: "{items}"
        }
I'm not retreiving the items as they should be.

**Comment by draperd** [comment] 2015-11-23 09:35
Have you reviewed the JSDoc (http://dev.alfresco.com/resource/docs/aikau-jsdoc/AlfDynamicPayloadButton.html) to see how you can map the incoming publication to the payload for the button?

**Comment by shazada** [comment] 2015-11-23 09:39
Hi Dave,

I probably didn't :). I thought it was the subscriptionTopic which subscribes to the topic and automatically receives the payload. I'll read though the documentation and see if that works.

**Comment by shazada** [comment] 2015-12-01 14:20
Hi Dave, I've finally got it working somehow but it breaks the Filtered Search counter. I'll file a Jira issue for it. My code is:
```javascript
registerSubscriptions: function contezza_search_DownloadResults__registerSubscriptions() {
            this.alfSubscribe("CNTZ_DOWNLOAD_SEARCH", lang.hitch(this, this.onDownloadSearch));
            this.alfSubscribe("CNTZ_DOWNLOAD_RESULTS_SUCCESS", lang.hitch(this, this.onDownloadResults));
        }

onDownloadSearch: function contezza_search_DownloadResults__onDownloadSearch(payload) {
            this.alfLog("error", "onDownloadSearch:", payload, this);
            payload.pageSize = this.pageSize;
            payload.alfResponseTopic = "CNTZ_DOWNLOAD_RESULTS";
            this.alfPublish("ALF_SEARCH_REQUEST", payload, true);
        }
```
faceted-search.get.js:
```javascript
var actionDynamicResults = {
    name: "alfresco/buttons/AlfDynamicPayloadButton",
    config: {
        label: "DOWNLOAD Results",
        publishTopic: "CNTZ_DOWNLOAD_SEARCH",
        publishPayloadSubscriptions: [{
            topic: "ALF_SEARCH_REQUEST"
        }],
        useHash: true,
        hashDataMapping: {
            "hashFragmentParameterName": "buttonPayloadProperty"
        }
    }
widget.config.widgets.push(actionDynamicResults);

var services = model.jsonModel.services.push("contezza/search/DownloadResults");
```

So what this basically does is: Do the search again and send the result to the ALF_DOWNLOAD_AS_ZIP.

**Comment by draperd** [comment] 2015-12-01 15:04
I understand why you've raised the JIRA issue, but I've had to close it as "Not a bug".... effectively you've done half a customization here. If you are going to customize the widgets on a page then you need to take responsibility for the resulting behaviour of that customization.

As I've said in the comment on the JIRA issue it should be possible for you to swap out the counter widget for your own implementation that can handle your changes to the publication.

Unless you can suggest a generic way of fixing the problem that is not tied to your specific customization then this is not something that we would be able to fix.

**Closed by draperd** 2015-12-01 15:04 UTC

**Comment by shazada** [comment] 2015-12-01 15:49
Hi Dave,

Thanks for the update, I've updated the jira so hopefully you can make it a suggestion issue to work on it.
