### ISSUE TITLE
tutorial #1: upload does not work

### ISSUE THREAD

**Issue by torstenwerner** [Alfresco/Aikau#804] opened 2016-01-28 20:22 UTC
I have tried tutorial #1. I can see the dropzone 'Drop files here to upload to this location' when i drag a file but no upload dialog appears after dropping. And no file is uploaded. I am using Mac OS. My code is here: https://github.com/torstenwerner/aikau-sample

**Comment by draperd** [comment] 2016-01-29 08:26
Thanks for raising this issue... I'll work through the first tutorial chapter today to see if I can reproduce the problem. We've recently done some work on the uploader and recently fixed a bug relating to upload (see https://issues.alfresco.com/jira/browse/AKU-784). However, on the version of Aikau referenced in your pom.xml (1.0.52) this should be working

**Comment by draperd** [comment] 2016-01-29 09:00
OK... I followed the tutorial and have been able to reproduce the problem. The issue is that the tutorial is missing the instruction to include the "alfresco/services/DialogService"... if you add this service then upload will work.

This problem has been introduced as a result of the upload changes in 1.0.52. Previously the "alfresco/services/UploadService" was creating it's own "alfresco/dialogs/AlfDialog" instance - however, this is not best practice - all dialogs should be created via the "alfresco/services/DialogService".

I'll raise a JIRA issue to update the tutorial - as this is a small change I should be able to get this done within the current sprint, so that the tutorial will be correct once 1.0.53 has been released.

**Comment by draperd** [comment] 2016-01-29 09:04
I've raised this issue to address the problem: https://issues.alfresco.com/jira/browse/AKU-810

**Comment by torstenwerner** [comment] 2016-01-29 09:34
I have updated my code and it works now. Thank you very much!

**Comment by MartinDoyleUK** [comment] 2016-02-02 09:38
Closing as issue resolved.

**Closed by MartinDoyleUK** 2016-02-02 09:38 UTC
