### ISSUE TITLE
Publish compatibility maxtric between aikau and alfresco share

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [Alfresco/Aikau#1324] opened 2016-12-05 03:00 UTC
Generated `share` project from archetype `org.alfresco:share-amp-archetype:2.2.0` depends on aikau version `1.0.39.5` and `org.alfresco:share:jar:classes:5.1.e`. First of all what is the last aikau version which can be used with share `5.1.e`? The second, could you please publish compatibily maxtrix with share and aikau versions? It is unclear which aikau versions are stable and which of them can be safely used with different share versions.

**Comment by draperd** [comment] 2016-12-05 09:30
The quickest way to determine the latest version of Aikau is to look at the our Maven repo interface (https://artifacts.alfresco.com/nexus/#nexus-search;quick~aikau) or check the release notes file (https://github.com/Alfresco/Aikau/blob/develop/aikau/ReleaseNotes.md).

Aikau is intended to be backwards compatible with all versions of Share from 5.0.d Community and 5.0.1 Enterprise onwards (as these contains the necessary Surf dependencies and configuration).

I'm not going to create a compatibility matrix for the simple reason that there would be little point. The question is not really one of compatibility but of support.

If you're an Enterprise customer and you have an issue with Share then a support ticket will an Aikau fix appearing both a new release and possibly a hot-fix release of the version of Aikau that the version of Share uses which will then be bundled into the next Share service pack or hotfix.

If you're a Community user and have an issue then it can get raised but you will be required to update to the latest version of Aikau that contains the fix. 

So we strive to ensure that all versions of Aikau are compatible and that there is are no regressions in new releases and have a large number of automated tests to ensure this. Some regressions do occasionally get through and when they do we fix them and ensure that a test is added to prevent them occurring again in the future.... but if an issue is found then it will always be fixed (because we focus on bugs first) and the fix will be included in the next release.

**Closed by draperd** 2016-12-05 09:30 UTC
