### ISSUE TITLE
alfresco/search/AlfSearchList: Search scope wrong when using hash and passing siteId (fix included)

### ISSUE THREAD

**Issue by tom-vandepoele** [Alfresco/Aikau#1336] opened 2016-12-09 13:19 UTC
aikau/src/main/resources/alfresco/search/AlfSearchList.js

> if (this.useHash === true)
>                {
>                   // Unfortunately we made the error of using "scope" on the URL hash and
>                   // "selectedScope" as the widget attribute. This means that we have to special
>                   // case useHash being set to true to use the appropriate value for the mode being used...
>                   siteId = (this.scope === "repo" || this.scope === "all_sites") ? "" : scope;
>                   scope = this.scope || scope.toLowerCase();
> }

If the scope is in the hash, and it's a siteId, this needs to be reversed:

> if (this.useHash === true)
>                {
>                   // Unfortunately we made the error of using "scope" on the URL hash and
>                   // "selectedScope" as the widget attribute. This means that we have to special
>                   // case useHash being set to true to use the appropriate value for the mode being used...
>                   scope = this.scope || scope.toLowerCase();
>                   siteId = (scope === "repo" || scope === "all_sites") ? "" : scope;
> }

Otherwise the payload will be

> scope: repo,
> repo: false

instead of 

> scope: some_site,
> repo: false

And you will get 0 search results when searching in a site scope

Please fix and commit. Thx.

**Comment by draperd** [comment] 2016-12-09 13:40
Thanks for raising this issue. What version of Alfresco / Aikau have you encountered this on please? I want to know where the fix needs to be applied (i.e. if there are any released versions of Alfresco this needs to be applied to?)

**Comment by tom-vandepoele** [comment] 2016-12-09 13:43
Alfresco 5.1.1.4
Aikau 1.0.67.1

The issue is still in the lastest version of Aikau (the current sources on GitHub)

**Comment by draperd** [comment] 2016-12-09 13:54
OK... I'm going to need to investigate this further. I've just tried this out on our current company installation (Alfresco 5.1.2, Aikau 1.0.67.5) and I can't reproduce the symptoms of the problem as you describe them (i.e. that no search results are found when the URL contains a siteId as the scope - both on initial search and refreshing with the value in the URL).

I'm not saying that we don't need to make a change, but the priority is not to break behaviour in Share so I'll need to do some further investigation and try out the change before I commit it.

**Comment by tom-vandepoele** [comment] 2016-12-09 14:12
I discovered the problem during a customization. I'd have to check the OOTB behaviour.

an example url for OOTB would be:

http://localhost:8080/share/page/site/some_site/dp/ws/faceted-search#searchTerm=test&query={"prop_cm_name":"","datatype":"cm:content"}&scope=some_site

with "some_site" a sitename.

**Comment by draperd** [comment] 2016-12-09 14:24
So that URL looks like something you'd get from an advanced search... I've just tested that and this is also still yielding results. I've just applied that exact URL hash to our instance of Share (with a different site name) and it still yields results.

What does the URL of the XHR request made to the Repository look like? Presumably you're seeing something wrong with that which is causing no results to be rendered?

**Comment by tom-vandepoele** [comment] 2016-12-09 14:32
I'll check later and try to reproduce with an OOTB alfresco. Need to finish up on another issue first. I'll get back to you in a few hours.

**Comment by tom-vandepoele** [comment] 2016-12-09 17:00
Ok, I can confirm there's no error in OOTB Alfresco. Scope and siteid arrive correctly before this code snippet is called.

I'm assuming some other customization on our end is the culprit. I'll figure it out and check if there's any good reason to change this code in aikau or not.

**Comment by draperd** [comment] 2016-12-09 17:14
OK, thanks - I'll close this issue for now, but feel free to re-open if you find anything related that needs addressing.

**Closed by draperd** 2016-12-09 17:14 UTC

**Comment by tom-vandepoele** [comment] 2016-12-09 17:28
For reference, discovered the cause: 

in our customization, the FCTSRCH_SCOPE_SELECTION_MENU widget has been removed, causing the ALF_SEARCHLIST_SCOPE_SELECTION event not to be fired, as it does in OOTB Alfresco.

In OOTB the onScopeSelection: function alfresco_search_AlfSearchList__onScopeSelection(payload) would be executed, setting the scope and siteId correctly.

The moment I put the widget back on the page everything worked again.

**Comment by draperd** [comment] 2016-12-09 17:37
Thanks for the info - much appreciated. I'm glad you got the issue resolved, are you happy then that nothing needs fixing. One option would be to just hide that element rather than removing it completely I guess?

**Comment by tom-vandepoele** [comment] 2016-12-12 09:22
Yes, or launch the ALF_SEARCHLIST_SCOPE_SELECTION event someplace else on the page, or extend the AlfSearchList to switch those 2 lines. I went with the former as it was quickest in my case.

For the future, it might be better to still switch those lines out (as I see it, it has no impact other than resolving this issue when someone removes the FCTSRCH_SCOPE_SELECTION_MENU widget from the page, and it prevents other developers from having to spend time on looking into this issue). 
But that's not for me to decide.

I'm happy to have a solution.
Thanks for the effort you spent on this!

**Comment by draperd** [comment] 2016-12-12 09:26
No problem - very happy to help!
