### ISSUE TITLE
PdfJS and thumbnail.get.js error

### ISSUE THREAD

**Issue by vincent-kali** [Alfresco/Aikau#1001] opened 2016-04-15 21:11 UTC
Hi,
Since aikau v1.0.39.5 (Alfresco 5.1.e), I'm facing issues when using AlfDocumentPreview widgets on PDF documents.
Steps to reproduce: (I detect this on my home made aikau page, but it can be reproduced on any aikau page which contains preview widget like faceted page):
1- Open faceted seach share page, and run query returning pdf and office documents ('pdf or xls')
2- Click on the thumbnail widget of the pdf file: open pdf preview, works fine.
3- Click on the thumbnail widget of the xls file: open xls preview, works fine.
4- Click on the thumbnail widget of the pdf file: error.
 Since a txt or MSoffice document has been previewed, it is not possible anymore to preview any pdf document (need page reload).

Log output: org.springframework.extensions.webscripts.WebScriptException: 03150001 The content node was not specified so the content cannot be streamed to the client: classpath*:alfresco/templates/webscripts/org/alfresco/repository/thumbnail/thumbnail.get.js)

PdfJs tries to get pdf thumbnail at following url which always return null value : /share/proxy/alfresco/api/node/workspace/SpacesStore/1a0b110f-1e09-4ca2-b367-fe25e4964a4e/content/thumbnails/pdf?c=force&noCache=1460754387703

Using last aikau release (1.0.63), pdf preview are just not loading.....
 
Any idea ?
Vincent

**Comment by draperd** [comment] 2016-04-18 08:22
Just to confirm, as you saying that once you've previewed any Microsoft Office document that it is no longer possible to preview any other without reloading the page?

**Comment by vincent-kali** [comment] 2016-04-18 08:32
No exactly:
Since aikau v1.0.39.5 (Alfresco 5.1.e): once previewed MS office or TXT document, it is no longer possible to preview any PDF document wihtout reloading the page (preview to MS Office or TXT document are still possible).
I just tested the last aikau release (1.0.63), and PDFJS preview seems to not work at all.
This can be tested using the faceted search page.
Vincent

**Comment by draperd** [comment] 2016-04-18 08:33
We have unit tests for the AlfDocumentPreview and they all seem to be working fine. I'll test this out on an Alfresco instance though to be sure. Are you getting any errors appearing in your browser console or in the server stdout?

**Comment by vincent-kali** [comment] 2016-04-18 08:37
You sould be able to reprodure just by upgrading aikau to version 1.0.63 in Alfresco 5.1.e .
I'll give you all details I have shortly (what I get in console....)

**Comment by draperd** [comment] 2016-04-18 09:14
I've not been able to reproduce this using recent Aikau builds against 5.0.3... I'm just getting a 5.1 environment up and running to test against. Is there anything else about your environment that might be different at all?

**Comment by vincent-kali** [comment] 2016-04-18 09:58
Nothing specific, just deployed 201602 (5.1.e) release and upgrade aikau. Can't preview document USING AIKAU (YUI preview widgets in doc detail is working fine). You should be able to reproduce... please tell me

**Comment by draperd** [comment] 2016-04-18 14:21
OK... we've been able to reproduce this issue. This was introduced with an upgrade to new versions of the pdf.js library files in 1.0.61. The problem is that one of the new files appears to be causing the YUI compressor to break. Our unit tests are unaffected because we're using a much more recent version of the Surf than found in 5.1. We'll aim to have this fixing in the 1.0.64 release

**Comment by kevinroast** [comment] 2016-04-18 14:39
We have found an issue compressing the pdf.js project file with YUI Compressor lib. This will be fixed with this PR: https://github.com/Alfresco/Aikau/pull/1003

**Comment by draperd** [comment] 2016-04-18 15:20
There appears to be a follow on error that results in the preview displaying but just showing the loading spinner. We're continuing to look into this problem and will either have a resolution for 1.0.64 or roll back to the previous version of pdf.js for the 1.0.64 release.

**Comment by draperd** [comment] 2016-04-18 16:20
PR #1004 fixes this issue

**Comment by vincent-kali** [comment] 2016-04-18 20:20
Thanks for your feedback !
BTW did you also reproduce the PDF preview pbm ? (after any TXT or MS Office preview)

**Comment by draperd** [comment] 2016-04-19 07:13
No problem. I've not been able to reproduce the other problem that you've described. Once 1.0.64 is released perhaps you can see if you can reproduce it and then open another issue if it's still a problem and we'll look into it some more.

**Comment by vincent-kali** [comment] 2016-04-19 07:33
Fine. Thanks again.

**Comment by draperd** [comment] 2016-04-19 08:52
Fixed in 1.0.64 release which is now available.

**Comment by vincent-kali** [comment] 2016-04-19 18:32
No problem anymore using 1.0.64 release !

**Comment by vincent-kali** [comment] 2016-04-19 18:34
Any plan to implement the 'maximize' functionnality in preview to switch in full screen ?

**Comment by draperd** [comment] 2016-04-20 08:04
Not at the present time, it's not on our current backlog of features to implement.

**Closed by draperd** 2016-04-20 08:04 UTC

**Comment by vincent-kali** [comment] 2016-04-21 08:07
Is this backlog shared anywhere ? Is AIKAU roadmap published ?
Thanks

**Comment by draperd** [comment] 2016-04-21 08:12
There is no roadmap as such, just our sprint backlog: https://issues.alfresco.com/jira/secure/RapidBoard.jspa?rapidView=322&view=planning.nodetail

**Comment by vincent-kali** [comment] 2016-04-21 16:32
bad news..... I just reproduced the issue on another 5.1.e Platform with 1.0.64. Preview widget is displayed the waiting picture indefinitly....... It means that I have currently two platforms, I can reproduce on one Platform but not on the another one. Could you advise on what to check ? No log in browser console .....

**Comment by draperd** [comment] 2016-04-21 16:41
We validated this on both 5.1 Enterprise (not the Community release) and 5.0.3 Enterprise. The issue we were seeing is that there was YUI compressor error occurring that resulting in the spinner not disappearing. It might be worth ensuring that your browser cache is cleared to be 100% sure you're getting the updated version of the PDF.js libary (if clearing the caches does work, then this is also an issue we need to address). You can also set your browser to break on exceptions and see what the cause of the exception is.

**Comment by vincent-kali** [comment] 2016-04-21 16:47
clearing the caches does work.
thanks a lot for your help !!
